apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../nai-db

patches:
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: nai-db
      namespace: nai-db
    patch: |-
      - op: remove
        path: /spec/replica
      - op: add
        path: /spec/replica
        value:
          enabled: false
      - op: add
        path: /spec/backup
        value:
          barmanObjectStore:
            destinationPath: s3://nai-cnpg-dc02/
            endpointURL: http://10.42.245.71
            s3Credentials:
              accessKeyId:
                name: objects-creds
                key: ACCESS_KEY_ID
              secretAccessKey:
                name: objects-creds
                key: ACCESS_SECRET_KEY
            wal:
              compression: gzip
              maxParallel: 8
          retentionPolicy: "30d"
