apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nai-helm-admin
subjects:
  - kind: ServiceAccount
    name: nai-helm
    namespace: nai-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
