apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../templates/cluster/nkp-cluster

patches:
  - target:
      kind: Cluster
      name: nkp-cluster-template
    patch: |-
      - op: replace
        path: /metadata/name
        value: nkp-nai-02

      - op: add
        path: /metadata/labels/nai.nutanix.com~1profile
        value: agent-gateway

      - op: add
        path: /metadata/labels/nai.nutanix.com~1site
        value: dc02

      - op: replace
        path: /metadata/labels/konvoy.d2iq.io~1cluster-name
        value: nkp-nai-02

      - op: replace
        path: /spec/topology/variables/0/value/addons/ccm/credentials/secretRef/name
        value: nkp-nai-02-pc-credentials

      - op: replace
        path: /spec/topology/variables/0/value/addons/csi/providers/nutanix/credentials/secretRef/name
        value: nkp-nai-02-pc-credentials-for-csi

      - op: replace
        path: /spec/topology/variables/0/value/addons/konnectorAgent/credentials/secretRef/name
        value: nkp-nai-02-pc-credentials-for-konnector-agent

      - op: replace
        path: /spec/topology/variables/0/value/nutanix/prismCentralEndpoint/credentials/secretRef/name
        value: nkp-nai-02-pc-credentials

      - op: replace
        path: /spec/topology/variables/0/value/addons/serviceLoadBalancer/configuration/addressRanges/0/start
        value: "10.42.245.54"

      - op: replace
        path: /spec/topology/variables/0/value/addons/serviceLoadBalancer/configuration/addressRanges/0/end
        value: "10.42.245.54"

      - op: replace
        path: /spec/topology/variables/0/value/controlPlane/nutanix/machineDetails/cluster/name
        value: "PHX-MKT245"

      - op: replace
        path: /spec/topology/variables/0/value/controlPlane/nutanix/machineDetails/image/name
        value: "nkp-rocky-9.6-release-cis-1.34.1-20251206060914.qcow2"

      - op: replace
        path: /spec/topology/variables/0/value/controlPlane/nutanix/machineDetails/subnets/0/name
        value: "primary"

      - op: add
        path: /spec/topology/variables/0/value/globalImageRegistryMirror
        value:
          url: https://registry.nutanixdemo.com/bootcamps

      - op: replace
        path: /spec/topology/variables/0/value/nutanix/controlPlaneEndpoint/host
        value: "10.42.245.53"

      - op: replace
        path: /spec/topology/variables/0/value/nutanix/prismCentralEndpoint/url
        value: "https://mkt245-pc.internal.nutanixdemo.com:9440"

  # - target:
  #     kind: Secret
  #     name: pc-credentials
  #   patch: |-
  #     - op: replace
  #       path: /metadata/name
  #       value: nkp-nai-02-pc-credentials

  # - target:
  #     kind: Secret
  #     name: pc-credentials-for-csi
  #   patch: |-
  #     - op: replace
  #       path: /metadata/name
  #       value: nkp-nai-02-pc-credentials-for-csi

  # - target:
  #     kind: Secret
  #     name: pc-credentials-for-konnector-agent
  #   patch: |-
  #     - op: replace
  #       path: /metadata/name
  #       value: nkp-nai-02-pc-credentials-for-konnector-agent

# replacements:
#   - source:
#       kind: Cluster
#       fieldPath: metadata.name
#     targets:
#       - select:
#           kind: Secret
#         fieldPaths:
#           - metadata.labels.[konvoy.d2iq.io/cluster-name]
