apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nai-db
  namespace: nai-db
spec:
  instances: 1

  storage:
    size: 10Gi

  bootstrap:
    recovery:
      source: nai-db-dc01

  postgresql:
    parameters:
      max_connections: "1000"

  monitoring:
    enablePodMonitor: true

  externalClusters:
    - name: nai-db-dc01
      barmanObjectStore:
        destinationPath: s3://nai-db/dc01
        endpointURL: http://10.42.245.71
        s3Credentials:
          accessKeyId:
            name: objects-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: objects-creds
            key: ACCESS_SECRET_KEY
