apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nai-db-dc02
  namespace: nai-db
spec:
  bootstrap:
    recovery:
      source: nai-db-dc01
      database: nai_iep
      owner: nai-api-user
      secret:
        name: nai-db-app

  replica:
    enabled: true
    source: nai-db-dc01

  externalClusters:
    - name: nai-db-dc01
      barmanObjectStore:
        destinationPath: s3://nai-cnpg-dc01/
        endpointURL: http://10.42.245.71
        # serverName: nai-db
        s3Credentials:
          accessKeyId:
            name: objects-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: objects-creds
            key: ACCESS_SECRET_KEY
        wal:
          maxParallel: 8
