apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../nai-db
  - ../nai-system

patches:
  - path: patch-promote.yaml
    target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: nai-db-dc02
      namespace: nai-db
