apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nai-db
  namespace: nai-db
spec:
  instances: 1

  storage:
    size: 10Gi

  bootstrap:
    initdb:
      database: nai_iep
      owner: nai-api-user
      secret:
        name: nai-db-app

  postgresql:
    parameters:
      max_connections: "1000"

  monitoring:
    enablePodMonitor: true
