apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nai-system

resources:
  - ../../../templates/nai-system

configMapGenerator:
  - name: nai-operators-values
    files:
      - values.yaml=nai-downsized-values.yaml
  - name: nai-core-values
    files:
      - values.yaml=nai-downsized-values.yaml

generatorOptions:
  disableNameSuffixHash: true
