apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - management-workspaces.yaml
  - management-projects.yaml
  # - capi-cluster-dc01.yaml
  # - capi-cluster-dc02.yaml
  # - workload-components-dc01.yaml
  # - workload-components-dc02.yaml
  # - workspace-apps.yaml
  # - nai-db-dc01.yaml
