apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nai-capi-clusters
  namespace: kommander
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: nai-gitops
  path: ./management/capi-clusters
  prune: true
  wait: true
  timeout: 45m
  dependsOn:
    - name: nai-workspaces
