apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nai-workspace-apps
  namespace: nai-workspace
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: nai-gitops
    namespace: kommander
  path: ./management/workspaces/nai/apps
  prune: true
  wait: true
  timeout: 20m
  dependsOn:
    - name: nai-capi-cluster-dc01
    - name: nai-capi-cluster-dc02
