apiVersion: workspaces.kommander.mesosphere.io/v1alpha1
kind: Project
metadata:
  name: project-template
  namespace: nai-workspace
  annotations:
    kommander.mesosphere.io/description: ""
    kommander.mesosphere.io/display-name: project-template
spec:
  namespaceName: project-template
  placement:
    clusterSelector:
      matchLabels:
        nai.nutanix.com/profile: agent-gateway
  workspaceRef:
    name: nai-workspace
