apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - management-projects.yaml
  - workspace-apps.yaml
  - cluster-dc01.yaml
  - cluster-dc02.yaml
  - workload-components-dc01.yaml
  - workload-components-dc02.yaml
  - nai-db-dc01.yaml
  - nai-db-dc02.yaml
  - k8gb-dc01.yaml
  - k8gb-dc02.yaml
