apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nai-db-dc02
  namespace: nai-workspace
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: nai-gitops
    namespace: kommander
  path: ./workload/sites/dc02/nai-db
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
    - name: nai-db-dc01
  kubeConfig:
    secretRef:
      name: nkp-nai-02-kubeconfig
